targets:
  $default:
    sources:
      - lib/**
      - bin/**
      - test/**
      - cs2dart_roslyn_worker/**
      - pubspec.*
      - $package$
    builders:
      cs2dart|roslyn_worker:
        enabled: true
        generate_for:
          - cs2dart_roslyn_worker/**.cs
          - cs2dart_roslyn_worker/cs2dart_roslyn_worker.csproj
          - cs2dart_roslyn_worker/cs2dart_roslyn_worker.sln

builders:
  roslyn_worker:
    import: "package:cs2dart/src/build/roslyn_worker_builder.dart"
    builder_factories: ["roslynWorkerBuilder"]
    build_extensions:
      ".cs": [".dotnet_published"]
      ".csproj": [".dotnet_published"]
      ".sln": [".dotnet_published"]
    auto_apply: root_package
